# .github/workflows/preview.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          yarn install
          yarn build

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.PRP_TOKEN }}
          #   source-dir: ./build/
          #   umbrella-dir: pr-preview
          action: auto
          preview-branch: gh-pages
          source-dir: .
