# .github/workflows/preview.yml
name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          yarn install
          yarn build

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.PRP_TOKEN }}
          # source-dir: ./build/
          # action: auto
          preview-branch: gh-pages
          source-dir: ./dist/
          umbrella-dir: pr-preview
